### ISSUE TITLE
[BUG] azure-storage package installation error

### ISSUE THREAD

**Issue by loomlike** [recommenders-team/recommenders#1109]
### Description
```
    RuntimeError:

    Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.
```
### In which platform does it happen?
Linux (DSVM)

### How do we replicate the issue?
Remove conda env and reinstall

### Expected behavior (i.e. solution)
Let's pin azure* packages

**Comment by miguelgfierro** [comment]
Right now we don't have Azure dependencies anymore. Closing
