### ISSUE TITLE
[typo] in examples/03_evaluate/evaluation.ipynb

### ISSUE THREAD

**Issue by YanZhangADS** [recommenders-team/recommenders#1370]
### Description

"May be biased, and less explainable than MSE" --> replace MSE with MAE?
"Given a relency definition" --> correct "relency"

"2.1.2 How-to with the evaluation utilities
2.2.2 How-to with evaluation utilities"  --> rephrase and be consistent

"2.2.1 Relevancy of recommendation" --> the bullet points should be 2.2.3 and all later bullet points need to be adjusted

**Comment by gramhagen** [comment]
good catch, feel free to make a pr to address typos! =)

**Comment by unnati914** [comment]
I can open a PR
