### ISSUE TITLE
Recommendation diversity metrics

### ISSUE THREAD

**Issue by loomlike** [recommenders-team/recommenders#142]
I saw the results reporting diversity in SAR document.
Which lib did we use for that?

Also we can add other metrics such as user / item coverage, novelty, serendipity, etc.

**Comment by anargyri** [comment]
A couple of other good additions for ranking measures are Kendall and Spearman metrics (see Shani & Gunawardana).

**Comment by miguelgfierro** [comment]
this was done by @YanZhangADS
