### ISSUE TITLE
Python 3.7 Support

### ISSUE THREAD

**Issue by laserprec** [recommenders-team/recommenders#1511]
### Description
We should extend the support of `recommenders` to python 3.7.

### Expected behavior with the suggested feature
We should modify our CIs to run our checks in py37 and fix any relevant issue raised from it.

### Other Comments
@anargyri, I think you mentioned problems with numba in python3.7 in venv installation. Is there an existing issue we can link to? I can also take a look.

**Comment by anargyri** [comment]
@laserprec I found a solution to this (see the above PR) by installing Surprise from source (the issue was caused by the .pyx files in Surprise which apparently were compiled with an incompatible numpy version).

**Comment by laserprec** [comment]
@anargyri this is AWESOME! Thanks Andreas!
