### ISSUE TITLE
[FEATURE] AzureML SDK v2 support

### ISSUE THREAD

**Issue by shohei1029** [recommenders-team/recommenders#1833]
### Description

AzureML SDK v2 was GA at Ignite 2022. 
We saw the codes in [the examples](https://github.com/microsoft/recommenders/tree/main/examples) are based on SDK v1. 
Do we have any plans to update the examples to follow SDK v2?

**Comment by miguelgfierro** [comment]
hi @shohei1029, at the moment, our team doesn't have bandwidth to do this task. Is this something that you could support?

**Comment by miguelgfierro** [comment]
duplicate of #2066
