### ISSUE TITLE
[ASK] SAR with timedecay_formula= False won't work

### ISSUE THREAD

**Issue by jamie613** [recommenders-team/recommenders#1869]
### Description
How should I run SAR if I don't want to implement the time decay formula in SAR?

My model is constructed as:

model = SAR(
      col_user="userID",
      col_item="itemID",
      col_rating="rating",
      col_timestamp="timestamp",
      similarity_type= similarity_type,
      timedecay_formula = False
)

and when fitting the model, it shows:

237         if df[select_columns].duplicated().any():
--> 238             raise ValueError("There should not be duplicates in the dataframe")
    239 
    240         # generate continuous indices if this hasn't been done

ValueError: There should not be duplicates in the dataframe

Plese advise, thanks!

**Comment by gramhagen** [comment]
the error indicates you have duplicate (user, item, rating) entries in your dataframe. If you don't want to distinguish duplicates by timestamp you will need to drop them first.

```
new_df = df.drop_duplicates(subset=['userID', 'itemID', 'rating'])
model.fit(new_df)
```
