### ISSUE TITLE
[BUG] [examples] extra should be merged

### ISSUE THREAD

**Issue by wutaomsft** [recommenders-team/recommenders#1903]
### Description
Currently [examples] is a separate option not installed by default.  If the user tries to run the notebooks, they may get errors.  Given most users will try to run the example notebooks in their first try, it is important that they have smooth experiences.  Propose to merge [examples] option/extra to the main package.

Guiding principle should be that the user should be able to run the simplest examples without installing extras.

**Comment by wutaomsft** [comment]
@loomlike

**Comment by miguelgfierro** [comment]
I'll take this one
