### ISSUE TITLE
[ASK] Best model for mobile ecommerce solution

### ISSUE THREAD

**Issue by umair975** [recommenders-team/recommenders#1913]
What is the best/recommended model and architecture to offer product and vendor recommendations to users in a mobile app

mobile app is built using flutter. DB is azure mysql

How do I capture the data from the app like what products/vendors user have browsed, added to cart, marked favourite? Should I save these in mysql or using some other streaming data to store this massive data. 

How to I get this data and combine it with customer, product, vendor master info from mysql db?

What model to use to recommend:
Product/vendors 
best selling products
most rated
recommended products
you might be interested in
best rated products/vendors
all such recommendations for products and vendors 

I understand that I have to train the model but do I have to do this on continuous basis so it can consider new data like newly added products/vendors or it does this automatically based on learnings?

**Comment by miguelgfierro** [comment]
you can try lightgbm CPU version
