### ISSUE TITLE
[FEATURE] Support Python 3.10

### ISSUE THREAD

**Issue by wutaomsft** [recommenders-team/recommenders#1919]
Latest Azure Databricks (13) runs on Python 3.10

**Comment by simonzhaoms** [comment]
+ Python 3.11

**Comment by akkefa** [comment]
Any progress on this?

**Comment by jpzhangvincent** [comment]
Any update on supporting 3.10?

**Comment by lgabs** [comment]
Anyone working on this? :/

**Comment by jpzhangvincent** [comment]
This is really important because it hinders the ability to experiment on the colab platform since it only allows to use python3.10... Hope someone looks into this issue soon.

**Comment by daviddavo** [comment]
> * Python 3.11

Python 3.12 was released last month, perhaps this should be the new target? Python 3.8 will end its support in less than a year.

**Comment by lgabs** [comment]
any progress on this issue? :/

**Comment by SimonYansenZhao** [comment]
Support for Python 3.10 and 3.11 has been added.
