### ISSUE TITLE
the environment

### ISSUE THREAD

**Issue by zhl98** [recommenders-team/recommenders#1927]
When I use the `pip install recommenders[examples,gpu]` ,I can not get the tensorflow-gpu . On the contrary, I obtained the CPU version of TensorFlow. Also, i have run `conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1'.
If you know where I went wrong, could you tell me what to do? thank you.

**Comment by miguelgfierro** [comment]
you shouldn't get tensorflow-gpu, this is the old pypi package, you should get `tensorflow`. If your computer, you should make sure that when you use tensorflow, it works. For this, make sure you are linking the CUDA and CuDNN libraries correctly. I would start by just installing TF 2.7 https://github.com/recommenders-team/recommenders/blob/main/setup.py#L67 and see if it takes the GPUs.
