### ISSUE TITLE
[ASK] No module named 'recommenders' after installing recommenders in Colab

### ISSUE THREAD

**Issue by Shu-x** [recommenders-team/recommenders#1928]
### Description
Hello, I'm trying to use recommenders in Google Colab and I'm getting this error: No module named 'recommenders'.
I am using Python 3.8.10. 

I've tried
`!pip install recommenders`
`pip install git+https://github.com/microsoft/recommenders.git`

When I run `!pip show recommenders` it shows that it has been installed.
<img width="538" alt="image" src="https://user-images.githubusercontent.com/100437979/236729065-9f52b3f1-ac85-4e91-85bc-f5bdc39d3f67.png">

But when I run `recommenders.utils.timer import Timer` I get an error message.
<img width="481" alt="image" src="https://user-images.githubusercontent.com/100437979/236729148-e9f60816-23ce-457d-afde-698cb74e0389.png">

Does anyone know how to resolve this?

**Comment by Meshael-S** [comment]
I face the same issue and could not solve it
Waiting for help

**Comment by SebasAndres** [comment]
I'm having the same issue too! I've tried everything people suggested in the issue https://github.com/microsoft/recommenders/issues/1519, but it didn't work for me :sleeping: 

I'm using Pyspark through a virtual environment with Python 3.9.16. Somehow, the recommenders library works outside Jupyter Notebooks, but It doesn't work when I use it within the notebooks. If I do `!pip list`, the recommenders library is installed (1.1.1).

PD: Neither `pip install recommenders` nor `pip install git+https://github.com/microsoft/recommenders.git` worked for me.

Any suggestions :pray:?

**Comment by miguelgfierro** [comment]
`pip install recommenders` should work if you are in python>=3.6, <3.10. The default colab is 3.10, that's why it is not working. This is what I get when I open a colab:

```
import sys
print(sys.version)
3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]
```

3.10 is in the backlog, see https://github.com/microsoft/recommenders/issues/1919. We'll implement it as soon as we can.

**Comment by shasha920** [comment]
I faced same issue, anyone resolve it?
I try !pip install git+https://github.com/microsoft/recommenders.git
get ERROR: Package 'recommenders' requires a different Python: 3.10.12 not in '<3.10,>=3.6'

**Comment by miguelgfierro** [comment]
This is fixed with the new release

![image](https://github.com/recommenders-team/recommenders/assets/3491412/04e62249-2877-410c-80a6-b2e7dbb059ac)
