### ISSUE TITLE
[ASK] Remove deprecated Python settings from devcontainers.json

### ISSUE THREAD

**Issue by luabud** [recommenders-team/recommenders#1960]
### Description

Hi there!
I'm a PM for Python in VS Code, and I notice some of the Python extension's `python.linting` and `python.formatting` settings are being used in this repo's devcontainer.json file. These settings have been deprecated as in the latest Python extension pre-release version, as we're migrating our tooling support to extensions ([see here for more details](https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions)).

Because pylint is enabled for this repository, one workaround could be to include the new Pylint extension maintained by our team, and set the appropriate settings to use the pylint executable from the container itself.  For example:
```json
	"settings": { 
		"python.pythonPath": "/usr/local/bin/python",
		"python.languageServer": "Pylance",
		"pylint.importStrategy": "fromEnvironment",
		"pylint.path": ["/usr/local/py-utils/bin/pylint"]
	},

	"extensions": [
		"ms-python.python",
		"ms-python.vscode-pylance",
		"ms-python.pylint"
	],
```
Alternatively, the  `path` and `importStrategy` settings could be omitted so the pylint executable that is shipped with the Pylint extension is used instead (this approach would allow pylint to run faster than the one proposed above). 

### References

- https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions
- https://github.com/devcontainers/features/pull/625

Thanks!

**Comment by miguelgfierro** [comment]
This should be fixed in this PR https://github.com/recommenders-team/recommenders/pull/2167
FYI @SimonYansenZhao
