### ISSUE TITLE
[BUG] Wide and Deep model raise error --- no attribute 'NanLossDuringTrainingError'

### ISSUE THREAD

**Issue by Lulu20220** [recommenders-team/recommenders#1969]
### In which platform does it happen?

https://github.com/microsoft/recommenders/blob/main/examples/00_quick_start/wide_deep_movielens.ipynb
Following the notebook here, change my own dataset, but it runs into this error

```
AttributeError: module 'tensorflow._api.v2.train' has no attribute 'NanLossDuringTrainingError'
```

### How do we replicate the issue?

The dataset is very similar, wondering how different dataset would casue the problem

**Comment by miguelgfierro** [comment]
That notebook uses tf v1. 

If the data is very different, I would start from the current example in the repo and replace with the data you have until you get a reducing loss.
