### ISSUE TITLE
[ASK] is map_at_k in spark_evaluation actually at k?

### ISSUE THREAD

**Issue by spirosdim** [recommenders-team/recommenders#1990]
### Description
Hi, after looking at the [spark_evaluation.py](https://github.com/recommenders-team/recommenders/blob/staging/recommenders/evaluation/spark_evaluation.py#L350) the `map_at_k` method, I noticed that it uses [`meanAveragePrecision`](https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/mllib/evaluation/RankingMetrics.scala#L83) from _spark.mllib_.  
Should `map_at_k` use the [`meanAveragePrecisionAt`](https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/mllib/evaluation/RankingMetrics.scala#L99) instead? In this way, it will use the min(k, pred.length) restricting the calculation of MAP to the top k predictions. 
Is there something that I miss?

### Other Comments

- The current `map_at_k` could be named as just `map`, using `meanAveragePrecision` from _spark.mllib_. 
- The `map_at_k` could use the `meanAveragePrecisionAt` from _spark.mllib_.

**Comment by loomlike** [comment]
Thank you for the comment. I'm checking it and will get back to you soon! I also created an issue #2002 to enhance the test for the metrics.
