### ISSUE TITLE
[FEATURE] better name for test_dataset.py

### ISSUE THREAD

**Issue by loomlike** [recommenders-team/recommenders#1991]
### Description
test_dataset.py name is confusing. It actually tests `download_utils`.
We may consider renaming it to `test_download_utils.py`

**Comment by miguelgfierro** [comment]
yeah, completely agree

**Comment by miguelgfierro** [comment]
Fixed https://github.com/recommenders-team/recommenders/pull/1989#discussion_r1327192914
