### ISSUE TITLE
[FEATURE] Upgrade fastai to v2

### ISSUE THREAD

**Issue by SimonYansenZhao** [recommenders-team/recommenders#1992]
### Description

fastai has breaking changes in v2, which makes [the code in recommenders](https://github.com/recommenders-team/recommenders/actions/runs/6168006071/job/16739851647#step:3:2847) incompatible with fastai v2.  For example, [`CollabDataBunch`](https://github.com/fastai/fastai1/blob/15bc02c61673400178fbdaf3417485755c299561/fastai/collab.py#L50) is removed in [fastai v2](https://github.com/fastai/fastai/blob/master/fastai/collab.py).

### Expected behavior with the suggested feature

It should be compatible with fastai v2 because fastai v1 is not maintained.

### Other Comments
There are 3 repos related to fastai:
* [fastai1](https://github.com/fastai/fastai1): fastai v1
* [fastai2](https://github.com/fastai/fastai2): fastai v2 (archived)
* [fastai](https://github.com/fastai/fastai): fastai v2+

See also
* [Fastai V2 Upgrade Review Guide](https://forums.fast.ai/t/fastai-v2-upgrade-review-guide-whats-new-in-fastai-version-2/86626)
* https://github.com/recommenders-team/recommenders/pull/1988: https://github.com/recommenders-team/recommenders/pull/1988/commits/97deed179525b2f8bc6d4f68f973e7cfb9676f6f

**Comment by miguelgfierro** [comment]
@SimonYansenZhao do you think this issue is fixed?

**Comment by SimonYansenZhao** [comment]
> @SimonYansenZhao do you think this issue is fixed?

Yes
