### ISSUE TITLE
[FEATURE] Alternative to scrapbook to execute notebooks programmatically for tests

### ISSUE THREAD

**Issue by miguelgfierro** [recommenders-team/recommenders#2012]
### Description

Scrapbook is not being developed anymore, and it doesn't support Python 3.10 (See https://github.com/recommenders-team/recommenders/pull/1988#issuecomment-1712425248)

**Comment by miguelgfierro** [comment]
WIP: https://github.com/miguelgfierro/pybase/pull/73

**Comment by SimonYansenZhao** [comment]
@miguelgfierro I don't find any alternatives to scrapbook after googling.  The solutions, I think, may be
1. Use nbformat as you do in https://github.com/miguelgfierro/pybase/pull/73
2. Borrow and modify the functions like [`sb.glue()`](https://github.com/nteract/scrapbook/blob/main/scrapbook/api.py) as @anargyri said in the meeting and make them part of Recommenders.

For the 1st option, I saw you written the functions to do that, what else should we do?  I can try tomorrow.

**Comment by miguelgfierro** [comment]
Actually, option 2 is kind of what I was doing in 1. If you have time it would be great if you could try 1.

**Comment by miguelgfierro** [comment]
I think I have finished the functions, see https://github.com/miguelgfierro/pybase/pull/73

Man, they say the most difficult language in the world is Chinese, but I think it is regex. Thank goodness that we have ChatGPT.

@SimonYansenZhao  I'll start a PR soon to replace all the scrapbook

**Comment by miguelgfierro** [comment]
Fixed!
