### ISSUE TITLE
[BUG] error for pip install recommenders on windows for python 10

### ISSUE THREAD

**Issue by Sandy4321** [recommenders-team/recommenders#2020]
### In which platform does it happen?
local windows 11

### How do we replicate the issue?
pip install recommenders
ERROR: Ignored the following versions that require a different python version: 0.6.0 Requires-Python >=3.6, <=3.8; 0.7.0 Requires-Python >=3.6, <3.8; 1.0.0 Requires-Python >=3.6, <3.9; 1.1.0 Requires-Python >=3.6, <3.10; 1.1.1 Requires-Python >=3.6, <3.10
ERROR: Could not find a version that satisfies the requirement recommenders (from versions: none)
ERROR: No matching distribution found for recommenders

I have 
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

### Expected behavior (i.e. solution)
pip install recommenders
works on 
local windows 11 
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

**Comment by loomlike** [comment]
I believe Recommenders support up to python 3.9 at the moment.
Related issue: #1919
