### ISSUE TITLE
[BUG] frame.append is deprecated

### ISSUE THREAD

**Issue by daviddavo** [recommenders-team/recommenders#2023]
### Description
Using the append method of a pandas dataframe or series is deprecated.

- https://pandas.pydata.org/docs/whatsnew/v1.4.0.html#whatsnew-140-deprecations-frame-series-append

### In which platform does it happen?
Python >= 3.9

### How do we replicate the issue?
Use any method that uses append in a 3.9 environment and it will raise a FutureWarning

### Expected behavior (i.e. solution)
No warning raised

### Other Comments

Changing all the appends to concats is a straightforward task, it would be a good first issue. It would also be a step forward into #1919

**Comment by miguelgfierro** [comment]
@daviddavo is this fixed?

**Comment by daviddavo** [comment]
Yeah, it should be fixed with #2058
