### ISSUE TITLE
[FEATURE] Support `steps` to newsrec models

### ISSUE THREAD

**Issue by loomlike** [recommenders-team/recommenders#2044]
### Description
Currently `newsrec` models only support `epoch` training and the smoke-tests with `epoch = 1` take minutes for each notebook.
With a simple tweak to `base_model.fit()`, we can introduce `steps` parameters that constraint the number of batches to train.
Then, we can set `steps = 1` to the smoke test which will expediate the test time.

### Expected behavior with the suggested feature
Use `steps = 1` to all the smoke tests of the newsrec models.

**Comment by sumana-2705** [comment]
@loomlike @miguelgfierro 
Shall I work on this issue?

**Comment by miguelgfierro** [comment]
feel free

**Comment by miguelgfierro** [comment]
right now, we have a bug that prevents external contributors from running the tests. It is a security limit from MS. We need to find a workaround. See #1853

**Comment by sumana-2705** [comment]
okayy, I understood. Thanks for your reply @miguelgfierro

**Comment by anargyri** [comment]
@loomlike @sumana-2705 should this issue be closed now?

**Comment by sumana-2705** [comment]
Yeah, I guess It can be closed now
