### ISSUE TITLE
[BUG] Migrate AzureML SDK from v1 to v2

### ISSUE THREAD

**Issue by SimonYansenZhao** [recommenders-team/recommenders#2066]
### Description

The AzureML SDK used in the testing for Recommenders is of [version v1](https://learn.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py) (named `azureml-core`):
https://github.com/recommenders-team/recommenders/blob/310370b2a0fd3366bce264b9b007ad6d6af330e0/.github/actions/azureml-test/action.yml#L75-L77
https://github.com/recommenders-team/recommenders/blob/310370b2a0fd3366bce264b9b007ad6d6af330e0/tests/ci/azureml_tests/submit_groupwise_azureml_pytest.py#L42-L50

Although v1 is still supported, It's better to migrate to [version v2](https://learn.microsoft.com/en-us/python/api/overview/azure/ai-ml-readme?view=azure-python&viewFallbackFrom=azure-ml-py) (named `azure-ai-ml`).  See [Upgrade to v2 -- Azure Machine Learning](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-migrate-from-v1?view=azureml-api-1)

### In which platform does it happen?

Azure Machine Learning

### How do we replicate the issue?

The SDK is used in all tests for Recommenders

### Expected behavior (i.e. solution)

AzureML SDK needs to be upgraded from v1 to v2, and all code in [tests/ci/azureml_tests/submit_groupwise_azureml_pytest.py](https://github.com/recommenders-team/recommenders/blob/main/tests/ci/azureml_tests/submit_groupwise_azureml_pytest.py) needs to be rewritten using v2.

**Comment by SimonYansenZhao** [comment]
In addition, an unresolved issue with the AzureML SDK v1 affects the upgrade of Recommenders is mentioned at https://github.com/recommenders-team/recommenders/pull/1937#issuecomment-1585972791.

**Comment by SimonYansenZhao** [comment]
The following items need to be considered:
* https://github.com/recommenders-team/recommenders/pull/2130#discussion_r1679231135
* https://github.com/recommenders-team/recommenders/pull/2098#discussion_r1664977970

**Comment by daviddavo** [comment]
It EOLs in September 2025. While more than a year remains, perhaps migrating to v2 would make Python 3.12 support easier too.
