### ISSUE TITLE
[ASK] Multi Modal Recommendation

### ISSUE THREAD

**Issue by zhaoyib** [recommenders-team/recommenders#2070]
### Description

Thank you for your amazing codes! That's really inspiring and helpful.

Will this repo add multi-modal related models and data in the future? I didn't find any relevant content in the current version and it is a very hot topic and something I am also very concerned about. I would be grateful if you could update the relevant content

**Comment by miguelgfierro** [comment]
@zhaoyib We have several examples of multimodal recommenders, like the news recommendation models (LSTUR, NPA, etc) that mixed interactions and text. If you are referring to things like images, it shouldn't be difficult to generate image embeddings and feed them to some of the algos. 

In any case, if you would like to contribute with a multimodal algo, please let us know, we will help you.
