### ISSUE TITLE
[FEATURE] Switch scipy sparse matrix to scipy sparse array

### ISSUE THREAD

**Issue by SimonYansenZhao** [recommenders-team/recommenders#2090]
### Description

As mentioned in [the doc of `scipy.sparse`](https://docs.scipy.org/doc/scipy/reference/sparse.html), the **scipy sparse matrix** interface will be deprecated and replaced by the **scipy sparse array** interface.  All code in Recommenders now use the scipy sparse matrix interface.  This issue may cause problems in the future if there is incompatibility or when the sparse matrix interface is completely deprecated.

### Expected behavior with the suggested feature

All scipy sparse matrix code should be replaced by code using scipy sparse array.

**Comment by miguelgfierro** [comment]
@SimonYansenZhao is this fixed with the latest PR https://github.com/recommenders-team/recommenders/pull/2083

**Comment by miguelgfierro** [comment]
@SimonYansenZhao can we close this issue?
