### ISSUE TITLE
[BUG] Can't download xdeepfmresources.zip

### ISSUE THREAD

**Issue by RuichongMa424** [recommenders-team/recommenders#2118]
Unable to log in https://recodatasets.z20.web.core.windows.net/deeprec/  and download content.
![image](https://github.com/recommenders-team/recommenders/assets/43717606/76d75d16-672a-450a-a667-f26fd7ab4439)

**Comment by miguelgfierro** [comment]
https://recodatasets.z20.web.core.windows.net/deeprec/xdeepfmresources.zip

This is working
