### ISSUE TITLE
Should I use jupyter notebook or vs code for this project [ASK] 

### ISSUE THREAD

**Issue by maushamkumar** [recommenders-team/recommenders#2132]
### Willingness to contribute

- [ ] Yes, I can contribute for this issue independently.
- [ ] Yes, I can contribute for this issue with guidance from Recommenders community.
- [ ] No, I cannot contribute at this time.

**Comment by miguelgfierro** [comment]
whatever you prefer :-)

VSCode has a Jupyter notebook extension that allows you to render a notebook inside the IDE. Or you can start your server and have the Jupyter notebook in the browser
