### ISSUE TITLE
[BUG] Issue with installing the recommenders package while building cornac on macOS ARM64 (M2)

### ISSUE THREAD

**Issue by Harikapl** [recommenders-team/recommenders#2173]
### Description
I am encountering an issue while trying to install the recommenders package on macOS ARM64 (Apple Silicon). The error occurs during the cornac building process, specifically while compiling the C++ source files. I've followed the instructions in the GitHub repository and tried installing via both pip and conda, but the issue persists.

### In which platform does it happen?
I am using VSCode as my development environment and have tried multiple approaches, including different compilers and package managers.

### My Setup:
macOS Version: macOS 14.3 (Sonoma)
Python Version: 3.10.12 (installed via pyenv and conda) and tried with 3.9 as well
Compiler:
Tried with clang++ and g++
Also tried Homebrew's LLVM and gcc
Package Managers:
Tried both pip and conda based on the instructions in the GitHub repository.

### Error Details
![image](https://github.com/user-attachments/assets/ef137865-28aa-40ad-9d07-bb9cff200856)

Additionally if I am trying to install through requirements file it fails saying while collecting cornac the dependencies are missing even if they are listed in the requirements file.

### Expected behavior (i.e. solution)
recommenders package installed without any issues

**Comment by joaovitorfranco** [comment]
I'm facing the same issue

**Comment by suvchr105** [comment]
Once you install Anaconda on your Mac, you can then retry. I have faced the same problem, but after installing Anaconda, it went off.
