### ISSUE TITLE
ordering top-k using argpartition() 

### ISSUE THREAD

**Issue by WessZumino** [recommenders-team/recommenders#275]
While writing the recommend_k_items() method for the rbm I noticed a small problem related to the argpartition() function. Basically, the returned k-items are not sorted in order, so a smaller number may appear earlier in the list than a bigger one. 

This seems to happen with real numbers that are very close, e.g. 4.979 vs 4.981 but it may affect other situations as well. The solution is provided below, more details in 

https://docs.scipy.org/doc/numpy/reference/generated/numpy.argpartition.html#numpy.argpartition

### *What* is affected by this bug?
1. recommend_k_items() method

This is used to select the top-k items in SAR

### *How* do we replicate the issue?
consider the following vector 
`a = np.random.rand(10000)*100`

I want the labels of the first 10 elements in decreasing order (biggest --> small), i.e. top_k=10
1) `id1 = np.argpartition(-a, top_k)[:top_k]`
returns: `array([8255, 1269, 1778, 9788, 8726, 5621, 5660, 9619, 8709, 6207], dtype=int64)`

Now we can check the actual values 
`a[id1] = array([99.97332566, 99.9455154 , 99.92515612, 99.94902373, 99.98342226,
       99.95773838, 99.93918414, 99.99000961, 99.92482682, 99.92437996])`

In the above example, 99.92 is positioned earlier than 99.94 or 99.98. In SAR, the function is used as 
`id1=  np.argpartition(a, -top_k)[-top_k:]` , giving:
`id1 = array([6207, 8709, 1778, 5660, 8726, 9788, 5621, 1269, 9619, 8255],dtype=int64)`
again, we can look at the actual values and find the same problem, just with a different order:
 
`a[id1]= array([99.92437996, 99.92482682, 99.92515612, 99.93918414, 99.98342226,
       99.94902373, 99.95773838, 99.9455154 , 99.99000961, 99.97332566])`

### Expected behavior (i.e. solution)

Solution 1: use full sorting algo like argsort
`id2 = np.argsort(-a)[:top_k]`, giving: 
`id2 = array([9619, 8726, 8255, 5621, 9788, 1269, 5660, 1778, 8709, 6207], dtype=int64)`
with values correctly ordered:
`a[id2] = array([99.99000961, 99.98342226, 99.97332566, 99.95773838, 99.94902373,
       99.9455154 , 99.93918414, 99.92515612, 99.92482682, 99.92437996])`

this solution is slower than `np.argpartition()`. 

Solution 2 (preferred): use top_k as a list
`id3 = np.argpartition(-a, range(top_k) )[:10]`, giving the same result of `argsort()`
`id3= array([9619, 8726, 8255, 5621, 9788, 1269, 5660, 1778, 8709, 6207], dtype=int64)`

benchmark: For a small array as the one considered in the example above the time difference of the two 
algos is negligible. However, for the movielens dataset, the user-affinity matrix is (6040, 3952), in this case 
`np.argsort() -->  1.2492165565490723`
`np.argpartition() --> 0.29970526695251465`

Therefore, solution 2 seems the preferred one

**Comment by victor-paltz** [comment]
There is an even faster solution with numpy:
`np.argpartition(a, range(-top_k, 0))[:,-1:-top_k-1:-1]`

It can be way faster than `np.argpartition(-a, range(top_k) )[:top_k]` in some situations because there is no need to compute -a

Here is a small benchmark:

![image](https://user-images.githubusercontent.com/40202673/129972883-f1f9b4ad-db0c-420b-b129-71a251174946.png)

**Comment by anargyri** [comment]
> There is an even faster solution with numpy:
> `np.argpartition(a, range(-top_k, 0))[:,-1:-top_k-1:-1]`
> 
> It can be way faster than `np.argpartition(-a, range(top_k) )[:top_k]` in some situations because there is no need to compute -a
> 
> Here is a small benchmark:
> 
> ![image](https://user-images.githubusercontent.com/40202673/129972883-f1f9b4ad-db0c-420b-b129-71a251174946.png)

This is not what we do though, we don't use `range`, see https://github.com/microsoft/recommenders/blob/efaa3d7742183dee0846877e2dc64977098e1977/reco_utils/common/python_utils.py#L97
