### ISSUE TITLE
Hi I keep getting the following Could not fetch URL https://pypi.python.org/simple/azureml-sdk/: There was a problem confirming the ssl certificate:

### ISSUE THREAD

**Issue by maximuslee1226** [recommenders-team/recommenders#381]
### *What* is affected by this bug?
*For example:*
* *Run of a notebook.*
* *Unit tests.*
* ...

### In *which* platform does it happen?
*For example:*
* *Azure Data Science Virtual Machine.*
* *Azure Databricks.*
* *Other platforms.*

### *How* do we replicate the issue?
(*Please be specific as possible. Use dashes (-) or numbers (1.) to create a list of steps.*)
*For example:*
* *Create a conda environment for pyspark*
* *Run unit test `test_sar_pyspark.py` with `pytest -m 'spark'`*
* ...

### Expected behavior (i.e. solution)
*For example:*
* The tests for SAR PySpark should pass successfully.

**Comment by yueguoguo** [comment]
@maximuslee1226 did you try the test on an Azure DSVM? If so, after the creation of the conda environment, have you activated it?
