### ISSUE TITLE
Add a test pipeline for Databricks

### ISSUE THREAD

**Issue by miguelgfierro** [recommenders-team/recommenders#432]
### *What* is affected by this bug?
Explore the possibility of adding a test pipeline for Databricks. Azure devops now connects with databricks: https://docs.azuredatabricks.net/user-guide/notebooks/azure-devops-services-version-control.html

### In *which* platform does it happen?
* *Azure Databricks.*

**Comment by jreynolds01** [comment]
More generally, we need to have a strategy for managing test resources; both azure resources and user authentication. It seems like it makes the most sense to have 1 resource group that contains the resources required for running tests. Then, we probably want to leverage service principals to take care of the authentication through the build agents. Would defer to guidance from @dciborow or others with more expertise.

**Comment by jreynolds01** [comment]
i think the link above is more around using version control from within the databricks environment, so I'm not sure it helps a ton with testing.

**Comment by miguelgfierro** [comment]
Closing old issue, feel free to reopen if needed.
