### ISSUE TITLE
Add Movielens dataset to xDeepFM

### ISSUE THREAD

**Issue by miguelgfierro** [recommenders-team/recommenders#446]
After @Leavingseason finishes the PR of xDeepFM, we should do a notebook that showcase xDeepFM with Movielens. Maybe @yexing99 could help on this?

**Comment by yexing99** [comment]
Finished coding. it is under branch ye /reco_utils/recommender/xdeepfm_movielens.

**Comment by anargyri** [comment]
Has the Movielens xDeepFM code been moved somewhere else?

**Comment by miguelgfierro** [comment]
Closing old issue, feel free to reopen if needed.
