### ISSUE TITLE
Autoencoder models

### ISSUE THREAD

**Issue by luiscastro193** [recommenders-team/recommenders#526]
Have you considered adding models based on autoencoders? They look pretty interesting: https://arxiv.org/abs/1901.00415

**Comment by miguelgfierro** [comment]
Thanks for the suggestion Luis. We are in fact going to add this one https://github.com/miguelgfierro/sciblog_support/blob/master/Intro_to_Recommendation_Systems/Intro_Recommender.ipynb

**Comment by luiscastro193** [comment]
Awesome :)

**Comment by gramhagen** [comment]
this implementation also looks interesting: https://paperswithcode.com/paper/hybrid-recommender-system-based-on-autoe2

**Comment by miguelgfierro** [comment]
TODO: 

compare results with old code movielens results:https://github.com/NVIDIA/DeepRecommender/issues/11

**Comment by miguelgfierro** [comment]
Initial result: https://github.com/microsoft/recommenders/blob/autoencoder/notebooks/02_model/deep_autoencoder_deep_dive.ipynb

**Comment by miguelgfierro** [comment]
We added a couple of variational auto encoder examples
