### ISSUE TITLE
[HELP] Learning curves, metrics, logging to Azure ML Experiments

### ISSUE THREAD

**Issue by ghost** [recommenders-team/recommenders#979]
### Description

In order to use the algorithms for my specific datasets, I have been converting Jupyter Notebooks such as the deep-dive and getting started implementations to run experiments in Azure Machine Learning Service by following the hyperdrive examples. I'd like to capture plots such as learning curves, data, metrics and python logging calls to the Experiments in Azure. This would require changes to reco_utils, and I understand that other users may be using this repo on different platforms.

The algorithm implementations don't seem to have methods where we can call to create learning curve plots etc. In the case of RBM, as an example, there is a matplotlib plot that you can see if you are running locally in Jupyter, but this is not set up to be captured if the code is used in a training script that runs in an Azure ML Experiment.

Another improvement would be to capture information that could be uploaded to the Azure ML Experiment and then downloaded to view in Tensorboard.

What is the prescribed approach/guidance to be able to use the Run class to upload files, capture images, plots and record metrics in reco_utils? I've seen examples that checks for the availability or the Run class and sets a bool HAS_AML. Would the repo accept pull requests for these changes or is it best to fork, sync with recommenders as an upstream and go from there?

**Comment by yueguoguo** [comment]
I think the plotting and logging features of AzureML Service are quite generic and any metrics of interest can be recorded and visualized after a run of experimentation. The APIs designed in the AzureML Python SDK are quite handy and I am not sure if it is necessary to implement them in the `reco_utils` for the same purpose...

**Comment by elogicsal** [comment]
![image](https://user-images.githubusercontent.com/46599524/69148690-d7d10180-0aa2-11ea-866a-4448798f0334.png)

@yueguoguo - Here is an example of some instrumentation I did within reco_utils to be able to see how RBM training was proceeding.

**Comment by elogicsal** [comment]
@yueguoguo  - Here is another example in rbm.py. There is a matplotlib plot that we can see when it is running in a notebook, but when we run this in Azure we would need to call plt.savefig() and then run.upload_file() to upload the image to the experiment.

![image](https://user-images.githubusercontent.com/46599524/69148990-89703280-0aa3-11ea-899b-2d1041d48bd8.png)

**Comment by yueguoguo** [comment]
Thanks @elogicsal - this is awesome and makes total sense. Thanks for sharing! AzureML service provides the logging utilities in experimentation run for the convenience of getting the metrics and plots out of the experiments. We have some notebooks illustrating the use of AzureML for certain tasks like hyperparameter tuning but we did not cover every single bit of the powerful features of AzureML. Therefore, we recommend readers to go to repositories like https://github.com/Azure/MachineLearningNotebooks/blob/master/tutorials/tutorial-1st-experiment-sdk-train.ipynb for useful information which is specific to AzureML.

**Comment by elogicsal** [comment]
@yueguoguo  - Will the team be receptive to pull requests to add instrumentation and plots using the HAS_AML check described above? These will be stored out to "./outputs" so that experimenters can download the information locally after the run.

**Comment by miguelgfierro** [comment]
We dropped the dependencies of Azure ml
